sudo: false
language: node_js
node_js:
- stable
install: true
deploy:
  provider: s3
  access_key_id: AKIAI7RVQWYD3EQD4EZA
  secret_access_key:
    secure: v1sRCXKQGpSSlF3afMBM1YJq1/bF7JSz+V9YV5+tT7JijkqkNY8voAaf6tcOirKFanbizMyIOlBbJGev3JPevTb0P8IX/4E+aok6I4X8s5C3W6zDnWFyvmeWkc5o578FKVW6Dwjh2VdsfebCBM4MKNh0zIcqNJLy3NM5HfHFE7QaND8363vc/I2xhXvZ12/8SAM5dbzAnfXgG3op0X5WpXN9QN5fua+cfoHu43T36Uc5XgdWOC7U1c24YX2XfDWrnnerdB506G0lEFADVtRuY5pCHrCrfbiSAgfMWxEmt5nEHC7h7/W62m6A8DZilh/xV0SbnYbgk7H+UcO/c4p0rID/u0RUZiuY02HDQajWg0O4yzvWmyzkq45xjtljMpgMUBOPZd0CdtLo8Kb3Aj8C1/bY9Hiw3skgU3/qq//HQml9/kT/uuxMd+fx20L+L+KBexIWoNe1IKV9gGOuVKqAQ3g2hKOs6v7Juwd2IvPRdg4MFMfNiFGhz3tSruiKow0NcS0J6ebkE8yy7Ix3t+uEWJchY5UC9VbPWC6g5025ilEGxNMufnw0i+4GYU+7ARgkG1AJwIGYiQ7Uw/9VuVo7ckeReb/wxGtkkZuY6aWkjK+/yaW/Ad+9sxzxTgmNa8qNUD25FckPOJqIqjO1T1I42tIERX3JWamWmOwMnjQhakQ=
  bucket: ulock.co
  local-dir: app
  acl: public_read
  on:
    repo: uLock/ulock-website
