sudo: false
language: node_js
node_js:
- stable
install: true
deploy:
  - provider: s3
    access_key_id: AKIAI7RVQWYD3EQD4EZA
    secret_access_key:
      secure: FoxmocKpZ9hjCJix4CyyXM1RmnKb+DppcnMNIGKxtR2+9Ul4aPJ7xuVzOV9a18b76xEm4DfX3Fg50UwVEMNunfDVENBWBtHQWTDD22/bFfLMhUUeOV3s/YtuzDz7OH5wYpvW9l7d/vM+agY1HLDOuFwkHQdjHBRl/LbhYt+e1A7qpyWJbFEpHlqJDmd6b2JQ+2IuQgiXiclc30R9H0IQAbRgyg/jos73ro9NDLAZQ/4Ly56c73SMNVQNBdxmfvUAkkgGZlKL07zBBsp44vJOjK0gasoRwH1UvHfFEfS8burJ9ujMzs9yTqnVojeLmtuAvvGdlEgzgn8C+hOTYz8ghIa4ya1RkCk+DqCkvJucqimkUwtGPFi4dS0tG1wuyimFTCoiJsrGUKetnUNPLmgu7ssnpfZhx0nzns2DP890RhQ1h1kmJ31JN9IeR9oPdvCbmSVBpvSBf8woqMPWeurlxFUDXJ1Mjzz1k8uydNDEpiBQFMcmyXLmdp0FFQuBFfNChxtWdMBSBYj+1jEgvGsjL5FOlOaAL05Z6C3WJNJCpfKHOj70x1F44BqXxQsKNWzGdKALE9M1TqYLgHXgR60XT3SUv0s1ERawUditXLUk5uuekOjJ2eNTUE/aa1XTeDgknqT/vk3DjaxOYtMLUX7jMGU84xQd5ZaJBtwSPx5tZ3k=
    bucket: ulock-website
    local-dir: app
    acl: public_read
    skip_cleanup: true
    detect_encoding: true
    on:
      branch: master
      repo: uLock/ulock-website
